server:
  port: 9000

spring:
  application:
    name: demo-oauth2-authorization-server
  cloud:
    aws:
      credentials:
        profile:
          name: backend-developer
  config:
    import: aws-parameterstore:/devops/demo-auth2-client/mysql?prefix=spring.datasource

logging:
  level:
    org.springframework.security: debug
    io.awspring.cloud: debug
